// Code generated by MockGen. DO NOT EDIT.
// Source: ./plan.go
//
// Generated by this command:
//
//	mockgen -source=./plan.go -destination=./mock_services/plan.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	model "gozero/server/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPlanService is a mock of PlanService interface.
type MockPlanService struct {
	ctrl     *gomock.Controller
	recorder *MockPlanServiceMockRecorder
	isgomock struct{}
}

// MockPlanServiceMockRecorder is the mock recorder for MockPlanService.
type MockPlanServiceMockRecorder struct {
	mock *MockPlanService
}

// NewMockPlanService creates a new mock instance.
func NewMockPlanService(ctrl *gomock.Controller) *MockPlanService {
	mock := &MockPlanService{ctrl: ctrl}
	mock.recorder = &MockPlanServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanService) EXPECT() *MockPlanServiceMockRecorder {
	return m.recorder
}

// CreatePlan mocks base method.
func (m *MockPlanService) CreatePlan(ctx context.Context, plan *model.Plan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlan", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePlan indicates an expected call of CreatePlan.
func (mr *MockPlanServiceMockRecorder) CreatePlan(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlan", reflect.TypeOf((*MockPlanService)(nil).CreatePlan), ctx, plan)
}

// DeletePlan mocks base method.
func (m *MockPlanService) DeletePlan(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlan", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlan indicates an expected call of DeletePlan.
func (mr *MockPlanServiceMockRecorder) DeletePlan(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlan", reflect.TypeOf((*MockPlanService)(nil).DeletePlan), ctx, id)
}

// GetPlan mocks base method.
func (m *MockPlanService) GetPlan(ctx context.Context, id int64) (*model.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlan", ctx, id)
	ret0, _ := ret[0].(*model.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlan indicates an expected call of GetPlan.
func (mr *MockPlanServiceMockRecorder) GetPlan(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlan", reflect.TypeOf((*MockPlanService)(nil).GetPlan), ctx, id)
}

// ListPlans mocks base method.
func (m *MockPlanService) ListPlans(ctx context.Context) ([]*model.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlans", ctx)
	ret0, _ := ret[0].([]*model.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlans indicates an expected call of ListPlans.
func (mr *MockPlanServiceMockRecorder) ListPlans(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlans", reflect.TypeOf((*MockPlanService)(nil).ListPlans), ctx)
}

// UpdatePlan mocks base method.
func (m *MockPlanService) UpdatePlan(ctx context.Context, plan *model.Plan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlan", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlan indicates an expected call of UpdatePlan.
func (mr *MockPlanServiceMockRecorder) UpdatePlan(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlan", reflect.TypeOf((*MockPlanService)(nil).UpdatePlan), ctx, plan)
}
